name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ucrt64
    - uses: actions/checkout@v3
    - name: Install Rust & Lua
      run: |
        pacman -S --noconfirm mingw-w64-ucrt-x86_64-rust mingw-w64-ucrt-x86_64-lua mingw-w64-ucrt-x86_64-pkgconf
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: luamemmy
        path: target/release/luamemmy.dll
        
